name: arm-none-eabi-gcc

on:
  workflow_call:
    inputs:
      pre-build:
        description: "Pre-build steps to run"
        default: ""
        required: false
        type: string
      arch:
        description: "Architecture flags passed to arm-none-eabi-gcc"
        required: true
        type: string
      args:
        description: "Additional CMake arguments -D <var>[:<type>]=<value>"
        default: ""
        required: false
        type: string
      target:
        description: "CMake targets to build"
        default: "all"
        required: false
        type: string
      post-build:
        description: "Post-build steps to run"
        default: ""
        required: false
        type: string

jobs:
  arm-none-eabi-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Run pre-build steps
        run: ${{ inputs.pre-build }}
      - uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1
      - run: cmake -Bbuild -DARCH=${{ inputs.arch }} -DCMAKE_TOOLCHAIN_FILE=CMakeModules/cmake/toolchain-arm-none-eabi-gcc.cmake ${{ inputs.args }}
      - run: cmake --build build --parallel --target ${{ inputs.target }}
      - name: Run post-build steps
        run: ${{ inputs.post-build }}
