name: build

on:
  push:
    branches: [master]

jobs:
  arm-none-eabi-gcc:
    uses: ./.github/workflows/arm-none-eabi-gcc.yml
    with:
      arch: -mcpu=cortex-m4
      target: .github-workflows

  esp-elf-gcc:
    uses: ./.github/workflows/esp-elf-gcc.yml
    with:
      path: tests/esp_hello_world
      target: esp32

  x86_64-linux-gnu-gcc:
    uses: ./.github/workflows/x86_64-linux-gnu-gcc.yml
    with:
      args: -DCMAKE_BUILD_TYPE=Release
      target: .github-workflows .github-workflowsTests