name: ctest

on:
  workflow_call:
    inputs:
      args:
        description: 'Additional CMake arguments -D <var>[:<type>]=<value>'
        default: ''
        required: false
        type: string
      target:
        description: 'CMake test target'
        default: ${{ github.event.repository.name }}Tests
        required: false
        type: string

jobs:
  x86_64-linux-gnu-gcc:
    # TODO
    # https://github.com/nektos/act/issues/1875
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/x86_64-linux-gnu-gcc.yml@v0.0.3
    with:
      args: ${{ inputs.args }}
      target: ${{ inputs.target }}
      upload-artifact: true

  ctest:
    needs: x86_64-linux-gnu-gcc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3.0.2
        with:
          name: build.tar
          path: .
      - run: tar -xvf build.tar
      - run: ctest --test-dir build --schedule-random --timeout 86400