name: esp-elf-gcc

on:
  workflow_call:
    inputs:
      pre-build:
        description: 'Pre-build steps to run'
        default: ''
        required: false
        type: string
      path:
        description: "Relative path under $GITHUB_WORKSPACE to place the repository"
        default: ""
        required: false
        type: string
      esp_idf_version:
        description: "Version of ESP-IDF docker image to use"
        default: "master"
        required: false
        type: string
      target:
        description: "ESP32 variant to build for"
        default: "esp32"
        required: false
        type: string
      command:
        description: "Command to run inside the docker container (default: builds the project)"
        default: "idf.py build"
        required: false
        type: string
      post-build:
        description: 'Post-build steps to run'
        default: ''
        required: false
        type: string
      upload-artifact:
        description: 'Upload build folder as artifact "build.tar"'
        default: false
        required: false
        type: boolean

jobs:
  esp-elf-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Add toolchain PPA
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update -y
          sudo apt install -y gcc-13 g++-13
      - name: Run pre-build steps
        run: ${{ inputs.pre-build }}
      - name: Install ESP-IDF
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b ${{ inputs.esp_idf_version }} --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh ${{ inputs.target }}
      - run: |
          . $HOME/esp/esp-idf/export.sh
          cd $GITHUB_WORKSPACE/${{ inputs.path }}
          ${{ inputs.command }}
      - name: Run post-build steps
        run: ${{ inputs.post-build }}
      - if: ${{ inputs.upload-artifact }}
        run: tar -cvf build.tar build # https://github.com/actions/upload-artifact#limitations
      - if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build.tar
          path: build.tar