name: license-checker

on:
  workflow_call:

jobs:
  license-checker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Check license
        uses: kt3k/license_checker@v1.0.6
