name: x86_64-linux-gnu-gcc

on:
  workflow_call:
    inputs:
      args:
        description: 'Additional CMake arguments -D <var>[:<type>]=<value>'
        default: ''
        required: false
        type: string
      target:
        description: 'CMake targets to build'
        default: 'all'
        required: false
        type: string
      upload-artifact:
        description: 'Upload build folder as artifact "build.tar"'
        default: false
        required: false
        type: boolean

jobs:
  x86_64-linux-gnu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build
      - run: cmake -Bbuild ${{ inputs.args }}
        env:
          CC:   gcc-13
          CXX:  g++-13
      - run: cmake --build build --parallel --target ${{ inputs.target }}
      # https://github.com/actions/upload-artifact#limitations
      - if: ${{ inputs.upload-artifact }}
        run: tar -cvf build.tar build
      - if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build.tar
          path: build.tar