name: x86_64-linux-gnu-gcc

on:
  workflow_call:
    inputs:
      pre-build:
        description: "Pre-build steps to run"
        default: ""
        required: false
        type: string
      args:
        description: "Additional CMake arguments -D <var>[:<type>]=<value>"
        default: ""
        required: false
        type: string
      target:
        description: "CMake targets to build"
        default: "all"
        required: false
        type: string
      post-build:
        description: "Post-build steps to run"
        default: ""
        required: false
        type: string

jobs:
  x86_64-linux-gnu-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Run pre-build steps
        run: ${{ inputs.pre-build }}
      - run: cmake -Bbuild ${{ inputs.args }}
      - run: cmake --build build --parallel --target ${{ inputs.target }}
      - name: Run post-build steps
        run: ${{ inputs.post-build }}
